const EventNames = {
  Atbash: 'atbash',
  Code: 'code',
  Crypt: 'crypt',
  KeyPress: 'keyPress',
  KeyCheck: 'checkKey',
  KeyIncrease: 'increaseKey',
  KeyDecrease: 'decreaseKey',
  KeyValue: 'keyValue',
  Keywords: 'keywords',
  KeywordType: 'keywordType',
  KeywordFirst: 'firstKeyword',
  KeywordSecond: 'secondKeyword',
  OwnAlphabet: 'ownAlphabet',
  OwnOption: 'ownOption',
  OwnValue: 'ownValue',
  Ciphertxt: 'codtxt',
  CiphertextAlphabet: 'ciphertextabc',
  PlaintextAlphabet: 'plaintextabc',
  Plaintxt: 'orgtxt',
  SetAlphabet: 'setAlphabet',
  Toggle: 'toggle',
  ToggleAlphabetOptions: 'toggleAlphabetOptions',
  ToggleDisplayOptions: 'toggleDisplayOptions',
  WarningClash: 'warnClash',
  WarningLength: 'warnLength',
};
export default EventNames;

